Make bus substitution optional
Bus substitution is not implemented for most buses for which it is
currently required: I²C is supported, but SPI, HID and SCSI are not.

Trying to rename the temperature sensor from a specific hard drive with:

	chip "drivetemp-scsi-0-0"
	label temp1 "Samsung 840 EVO"

currently results in:

	Error: [...]: Undeclared bus id referenced
	sensors_init: Can't parse bus name

While bus substitution should still be implemented for these missing
buses, it may also be overkill in a lot of scenarios.  Like the example
above (drivetemp chips), assuming a typical and fairly stable hardware
configuration.

To simplify things, make bus substitution optional, and allow users to
configure their system directly with bus numbers, even if they might be
unstable.

Related: #230 ("cannot label 'drivetemp' sensors - bus handling for scsi
busted?")
Related: #369 ("Undeclared bus id referenced")